services:

  auth-db:
    image: postgres:16-alpine
    container_name: authentication-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: auth-service
    container_name: auth-container
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL_PODMAN}
      - DB_USER=admin
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
    volumes:
      - ${USERPROFILE}/.aws:/home/appuser/.aws:ro
    depends_on:
      auth-db:
        condition: service_healthy

volumes:
  postgres_data:
    external: true
